services:

  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  react:
    build: ./react
    ports:
      - "80:80"
    volumes:
      - ./react:/app
    environment:
      - NODE_ENV=production
      - VITE_APP_VER=1.0.0
    depends_on:
      - server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5