version: '3'

services:

  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  react:
    build: ./react
    ports:
      - "80:80"
    volumes:
      - ./react:/app
    environment:
      - NODE_ENV=production



