apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-express-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-express-app
  template:
    metadata:
      labels:
        app: react-express-app
    spec:
      containers:
        - name: react
          image: 'nikolabod/react:latest'
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "2Gi"
              cpu: "250m"
        - name: server
          image: 'nikolabod/server:latest'
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-express-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: react-express-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
