apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-express-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-express-app
  template:
    metadata:
      labels:
        app: react-express-app
    spec:
      containers:
        - name: react
          image: 'nikolabod/react:latest'
          ports:
            - containerPort: 3000
        - name: server
          image: 'nikolabod/server:latest'
          ports:
            - containerPort: 4000
