apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: server