kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: 'nikolabod/react:latest'
          env:
          - name: NODE_ENV
            value: "production"        
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: "1Gi" 
              cpu: "1000m" 
            limits: 
              memory: "2Gi" 
              cpu: "1000m" 
          ports:
            - containerPort: 80