kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: 'nikolabod/react:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000