apiVersion: v1
kind: Service
metadata:
  name: react-load-balancer
  labels:
    app: react
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: react