apiVersion: v1
kind: Service
metadata:
  name: react-load-balancer
  labels:
    app: react
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: react