kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 'nikolabod/server:latest'
          resources: 
            requests: 
              memory: "512Mi" 
              cpu: "500m" 
            limits: 
              memory: "512Mi" 
              cpu: "500m"
          ports:
            - containerPort: 4000