kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 'nikolabod/server:latest'
          env:
          - name: NODE_ENV
            value: "production"
          livenessProbe:
            httpGet:
              path: /api/v1/healht
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: "512Mi" 
              cpu: "500m" 
            limits: 
              memory: "512Mi" 
              cpu: "500m"
          ports:
            - containerPort: 4000