kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 'nikolabod/server:latest'
          env:
          - name: NODE_ENV
            value: "production"
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: "2Gi" 
              cpu: "800m" 
            limits: 
              memory: "2Gi" 
              cpu: "800m" 
          ports:
            - containerPort: 4000