apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-express-api
  ports:
  - name: backend
    port: 4000
    targetPort: 4000
  - name: fronend:
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: react-express-api